// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2yXRn-zgkmF-d-KQs25I4wG4Qx0tSis',
    appId: '1:814513452881:android:f5d5b135efd3d837c74570',
    messagingSenderId: '814513452881',
    projectId: 'e-money-de6c3',
    storageBucket: 'e-money-de6c3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHrjWQmWK82nLKFsr7T95Q1BNubvkZsQ',
    appId: '1:814513452881:ios:6e518874804fc033c74570',
    messagingSenderId: '814513452881',
    projectId: 'e-money-de6c3',
    storageBucket: 'e-money-de6c3.firebasestorage.app',
    iosBundleId: 'com.example.dompetKampusGlobal',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBu4A2Yu1qiax9OYCqag1NWhx6Cawj3s',
    appId: '1:814513452881:web:fc63fc564237a187c74570',
    messagingSenderId: '814513452881',
    projectId: 'e-money-de6c3',
    authDomain: 'e-money-de6c3.firebaseapp.com',
    storageBucket: 'e-money-de6c3.firebasestorage.app',
    measurementId: 'G-DGR2R7M7HM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHrjWQmWK82nLKFsr7T95Q1BNubvkZsQ',
    appId: '1:814513452881:ios:6e518874804fc033c74570',
    messagingSenderId: '814513452881',
    projectId: 'e-money-de6c3',
    storageBucket: 'e-money-de6c3.firebasestorage.app',
    iosBundleId: 'com.example.dompetKampusGlobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsBu4A2Yu1qiax9OYCqag1NWhx6Cawj3s',
    appId: '1:814513452881:web:f495a7381732b37ac74570',
    messagingSenderId: '814513452881',
    projectId: 'e-money-de6c3',
    authDomain: 'e-money-de6c3.firebaseapp.com',
    storageBucket: 'e-money-de6c3.firebasestorage.app',
    measurementId: 'G-NTCBTHHV4R',
  );
}
